---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download

- hosts: k3s_masters
  become: yes
  roles:
    - role: k3s/master

- hosts: k3s_workers
  become: yes
  roles:
    - role: k3s/worker
