---
k3s_version: v1.24.2+k3s2
# this is the user that has ssh access to these machines
ansible_user: serverlocal
systemd_dir: /etc/systemd/system

# Set your timezone
system_timezone: America/New_York

# interface which will be used for flannel
flannel_iface: ens192

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: 10.254.11.5
primary_master_node: "{{ hostvars[groups['k3s_masters'][0]]['ansible_host'] | default(groups['k3s_masters'][0]) }}"
primary_master_ip: "{{ hostvars[groups['k3s_masters'][0]]['ip']['v4']['address'] | default(groups['k3s_masters'][0]['ip']['v4']['address']) }}"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: AFEQn9v8LJHFw9asldIG77

# change these to your liking, the only required one is--no-deploy servicelb
extra_server_args: "--no-deploy servicelb --no-deploy traefik --write-kubeconfig-mode 644 --tls-san '10.254.11.5' --tls-san 'k3s-lb-01' --disable 'servicelb' --disable 'traefik' --disable 'local-storage' --node-taint 'CriticalAddonsOnly=true:NoExecute'"
extra_agent_args: "--kubelet-arg node-status-update-frequency=5s"

# image tag for kube-vip
kube_vip_tag_version: v0.4.4

# image tag for metal lb
metal_lb_speaker_tag_version: v0.13.3
metal_lb_controller_tag_version: v0.13.3

# metallb ip range for load balancer
metal_lb_ip_range: '10.254.11.200-10.254.11.209'

# ntp server
ntp_server: 10.60.0.1